作業目標<br>
活用矩陣運算，實做線性代數<br>
作業重點<br>
線性代數公式應用<br>
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:<br>
array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [5]:
import numpy as np

In [12]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
array1_inv = np.linalg.inv(array1)
new = (array1_inv @ array1)
np.array_equal(new,np.identity(2))
# 很接進了!!

False

In [8]:
#2. 運用上列array計算特徵值、特徵向量?
np.linalg.eig(array1)

(array([13.,  2.]), array([[ 0.93632918, -0.70710678],
        [ 0.35112344,  0.70710678]]))

In [10]:
#3. 運用上列array計算SVD?
np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))